import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Transaction, Currency, CurrencyConfig } from '../types';

export const generatePDF = (transactions: Transaction[], currency: Currency = 'USD') => {
  const doc = new jsPDF();
  const currencySymbol = CurrencyConfig[currency].symbol;

  // Header Section
  doc.setFontSize(22);
  doc.setTextColor(79, 70, 229); // Primary color
  doc.text("Financial Transaction Report", 14, 22);

  // Metadata
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  const dateStr = new Date().toLocaleDateString() + ' ' + new Date().toLocaleTimeString();
  doc.text(`Generated on: ${dateStr}`, 14, 30);
  doc.text(`Transaction Count: ${transactions.length}`, 14, 35);
  doc.text(`Currency: ${currency}`, 14, 40);

  // Financial Summary
  const totalIncome = transactions
    .filter(t => t.type === 'income')
    .reduce((sum, item) => sum + item.amount, 0);
    
  const totalExpense = transactions
    .filter(t => t.type === 'expense')
    .reduce((sum, item) => sum + item.amount, 0);

  const netBalance = totalIncome - totalExpense;

  doc.setFontSize(11);
  doc.setTextColor(0, 0, 0);
  doc.text(`Total Income: ${currencySymbol}${totalIncome.toFixed(2)}`, 14, 50);
  doc.text(`Total Expenses: ${currencySymbol}${totalExpense.toFixed(2)}`, 80, 50);
  
  // Net Balance Color logic
  if (netBalance >= 0) {
    doc.setTextColor(16, 185, 129); // Green
  } else {
    doc.setTextColor(239, 68, 68); // Red
  }
  doc.text(`Net Balance: ${currencySymbol}${netBalance.toFixed(2)}`, 140, 50);

  // Table Configuration
  const tableColumn = ["Date", "Type", "Category", "Description", "Amount"];
  const tableRows = transactions.map(t => [
    t.date,
    t.type.charAt(0).toUpperCase() + t.type.slice(1),
    t.category,
    t.description + (t.merchant ? ` (${t.merchant})` : ''),
    `${t.type === 'expense' ? '-' : '+'}${currencySymbol}${t.amount.toFixed(2)}`
  ]);

  autoTable(doc, {
    head: [tableColumn],
    body: tableRows,
    startY: 60,
    theme: 'grid',
    headStyles: { 
      fillColor: [79, 70, 229],
      textColor: 255,
      fontStyle: 'bold'
    },
    styles: { 
      fontSize: 9,
      cellPadding: 3
    },
    columnStyles: {
      0: { cellWidth: 25 }, // Date
      1: { cellWidth: 20 }, // Type
      2: { cellWidth: 30 }, // Category
      3: { cellWidth: 'auto' }, // Description
      4: { cellWidth: 35, halign: 'right' }, // Amount
    },
    alternateRowStyles: {
      fillColor: [249, 250, 251]
    },
    didParseCell: (data) => {
        // Color amount text based on type
        if (data.section === 'body' && data.column.index === 4) {
            const rawAmount = data.cell.raw as string;
            if (rawAmount.includes('+')) {
                data.cell.styles.textColor = [16, 185, 129]; // Green
            } else {
                data.cell.styles.textColor = [239, 68, 68]; // Red
            }
        }
    },
    foot: [['', '', '', 'Net Balance', `${currencySymbol}${netBalance.toFixed(2)}`]],
    footStyles: {
      fillColor: [243, 244, 246],
      textColor: netBalance >= 0 ? [16, 185, 129] : [239, 68, 68],
      fontStyle: 'bold',
      halign: 'right'
    }
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for(let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by GeminiFin', 14, doc.internal.pageSize.height - 10);
    doc.text(`Page ${i} of ${pageCount}`, doc.internal.pageSize.width - 25, doc.internal.pageSize.height - 10);
  }

  // Save the PDF
  const fileName = `financial_report_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(fileName);
};